### ISSUE TITLE
Disable TLS

### ISSUE THREAD

**Issue by thedug** [dduportal/boot2docker-vagrant-box#13]
I added this to my Vagrantfile to disable TLS so that it is easy to get dev environment started.

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.provision "shell",
    inline: "echo 'DOCKER_TLS=no' >> /var/lib/boot2docker/profile; /etc/init.d/docker restart"
end

**Comment by tonivdv** [comment]
(y)

In the mean time, try https://github.com/YungSang/boot2docker-vagrant-box/issues/22#issuecomment-75027416

**Comment by thedug** [comment]
@tonivdv 

Thanks unless there is a compelling reason to enable TLS I'm going to leave it disabled.

**Comment by tonivdv** [comment]
Ah yes, I wrongly read your first comment. Seems today I'm doing too much at the same time (I'm missing the woman multi tasking gift ;p )

Thanks for sharing the disabling feature!

**Comment by dduportal** [comment]
Hi @thedug !

TLS should be enabled by default, as this is a default behavior from Docker.

Anyway, as @tonivdv pointed out, you can automate the process thru bootlocal.sh (disabling TLS or copying the certs).

Thanks for all those things !
