### ISSUE TITLE
Rsync error

### ISSUE THREAD

**Issue by pouicr** [dduportal/boot2docker-vagrant-box#2]
Hi,

I have an issue using rsync on windows, behind a corporate proxy:

==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring proxy for Docker...
==> default: Configuring proxy environment variables...
==> default: Installing rsync to the VM...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

tce-load -wi rsync

Stdout from the command:

Downloading: rsync.tcz
Error on rsync.tcz

Stderr from the command:

Connecting to repo.tinycorelinux.net (89.22.99.37:80)
wget: download timed out
md5sum: rsync.tcz.md5.txt: No such file or directory

However, if i connect the vm and run "tce-load -wi rsync" it works fine :(

Any ideas ?

**Comment by dduportal** [comment]
For info, the recent release v1.5.0 make rsync embedded : no more tce-load to do. (See the internal acceptance tests for seeing the non regression)
