### ISSUE TITLE
vagrant destroy should cause nfs to stop serving the exports

### ISSUE THREAD

**Issue by kevpie** [dduportal/boot2docker-vagrant-box#28]
After performing a `vagrant destroy` the entries were cleared from `/etc/exports`, however the nfs daemon was not restarted and continued to service the recently purged entries.

`==> default: Pruning invalid NFS exports. Administrator privileges will be required...`

`/etc/exports` is empty.

```bash
$ showmount -e
Exports list on localhost:
/opt/boot2docker                    192.168.10.10
```

**Comment by dduportal** [comment]
Hello @kevpie  !

Thank you for reporting this issue.

Is this related to vagrant itself, or just specific to the use of my basebox ?

**Comment by kevpie** [comment]
I haven't tested any other configurations, so I can't tell if it is related to vagrant or your basebox.   I'll have to test with a non boot2docker basebox to isolate that.  It won't be today.

**Comment by dduportal** [comment]
Hello @kevpie , it seems related to vagrant, see the v1.7.4 changelog : https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md#174-july-17-2015 .

Thanks for reporting !

Feel free to re-open this issue if you still reproduce and have more information to help us determinate if this is my basebox or vagrant issue, i'll help you dig around.
