### ISSUE TITLE
Version 1.7.1 not available

### ISSUE THREAD

**Issue by CharlieC3** [dduportal/boot2docker-vagrant-box#35]
Looks like version 1.7.1 was taken down from Drop Box. We have some developers that are unable to pull this specific version:

```
Loading metadata for box 'dduportal/boot2docker'
URL: https://atlas.hashicorp.com/dduportal/boot2docker
Adding box 'dduportal/boot2docker' (v1.7.1) for provider: virtualbox
Downloading: https://vagrantcloud.com/dduportal/boxes/boot2docker/versions/1.7.1/providers/virtualbox.box
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

The requested URL returned error: 404 Not Found
```

This no longer is there on dropbox https://dl.dropboxusercontent.com/u/2524496/boxes/boot2docker_virtualbox-1.7.1.box

**Comment by dduportal** [comment]
Hello !

Thank you very much for reporting that.
It seems that i accidentally deleted that ! I'll correct that asap.

I'm completely sorry for the inconvenience !

I'm thinking on how to improve next time (like : not depending on my personnal Dropbox) to not reproduce, but given i need a free solution, i don't know how to handle it. I'm open to ideas.


Btw, i'll notice you here by closing the issue when ok (i need a real web access instead of my phone)

**Comment by CharlieC3** [comment]
No worries, I switched them to start using the latest 1.8.1. As far as free storage, there aren't many options I know of! My only suggestion would be to create another email address, and use it to create a separate, "professional" Drop Box account to keep these things apart (Not sure if that would infringe on anything for Drop Box policy).

But as long as the artifacts are reliably available, I don't mind so much on the service being used!

**Comment by dduportal** [comment]
Hello !

First, the box has been repushed online with a corrected link. https://atlas.hashicorp.com/dduportal/boxes/boot2docker/versions/1.7.1/.

Tested here, even if Atlas GUI says "error", i could have download it with ```
vagrant box add --box-version 1.7.1 dduportal/boot2docker
```

Thanks dor the informations !
Seems like that, even with S3, the same problem could have occured, but seprating my personnal space storage withmy OSS one is a good start.

Also, i just discovered that Atlas can verify the box. I think it can be another point too : a nightly script that wil check.
