### ISSUE TITLE
Current directory mapped to the wrong path

### ISSUE THREAD

**Issue by ffung** [dduportal/boot2docker-vagrant-box#36]
Vagrant 1.7.4
Docker 1.8.1

https://github.com/dduportal/boot2docker-vagrant-box/pull/27 introduced mapping the host path the same path in the guest, which is very useful 

However the current directory determination in the template is off
`CURRENT_DIR = File.expand_path(File.dirname(__FILE__))`
sets the path to the expanded template of the box and not my own Vagrantfile. In my case it expands to 
```ruby
/Users/fai/.vagrant.d/boxes/dduportal-VAGRANTSLASH-boot2docker/1.8.1/virtualbox
```
This of course invalidates the purpose of https://github.com/dduportal/boot2docker-vagrant-box/pull/27

This also makes copying the certificates to your current host directory impossible, the instructions with regard to the bootlocal.sh is broken bc /vagrant is not mounted  
```sh
# Regenerate certs for the newly created Iprivate network IP
sudo /etc/init.d/docker restart
# Copy tls certs to the vagrant share to allow host to use it
sudo cp -r /var/lib/boot2docker/tls /vagrant/
```

My workaround for now is to just add the default synced folder back again:
```ruby 
config.vm.synced_folder ".", "/vagrant"
```

Not sure how to fix this maybe `Dir.pwd` will work for mounting the correct directory, but that still doesn't provide a fix with copying the certificates to your local host with bootlocal.sh; there's no deterministic way inside the guest to determine what your 'current host' mount directory is, especially if you have multiple synced_folders; passing the shell provisioner the current host directory seems like a viable solution

**Comment by dduportal** [comment]
Hello !

Thanks for reporting this bug :)

Your fix seems OK at short term to have a working behaviour again, can you please make me a pull request ? I'll merge that quickly since Docker 1.8.2 is on the go.


Considering the problem in a more global way, i think that we should dig in the vagrant codebase to understand how it determines the current folder. We are inside a Vagrantfile inheritance problem.
I'm quite sure we have access to parent/children attribute or special one in this case. I'm not a Ruby-dev but i think we can find something.

**Comment by ffung** [comment]
I think I resolved it, see https://github.com/dduportal/boot2docker-vagrant-box/pull/37

**Comment by dduportal** [comment]
Thank you !

Issue https://github.com/dduportal/boot2docker-vagrant-box/pull/37 merged to master, resolving the trick.

**Comment by dduportal** [comment]
Box released under atlas : https://atlas.hashicorp.com/dduportal/boxes/boot2docker/versions/1.8.2

Thank you again for contributing, feel free to reopen the issue if this does not works for you :)
