### ISSUE TITLE
Vagrant boot2docker does not auto rsync

### ISSUE THREAD

**Issue by ehernandez-xk** [dduportal/boot2docker-vagrant-box#46]
Hi I'm having problems with rsync_auto with Vagrant and using Docker as a provider, that means that I have a Docker Host VM (virtualBox).

Vagrant syncs my folder only in provision time(only once).

I want to sync my files on change (my machine <--> docker host)

    config.vm.box = "dduportal/boot2docker"

    config.vm.synced_folder ".", "/project", type: "rsync",
    rsync__auto: true

When I run **vagrant rsync-auto** it syncs my files correctly. but I want that Vagrant sync automatically. There is no error after **Vagrant up**

    dockerhost: Rsyncing folder: /Users/user/workspace/docker/provisioning/ => /project

I already tested to change /project directory permissions 777, does not work as well. 

Environment:

- Mac: OS X Yosemite, 10.10.5
- Vagrant: 1.8.1
- Docker: 1.10.2

**Comment by dduportal** [comment]
Hello @ehernandez-xk !

As stated by [Vagrant documentation](https://www.vagrantup.com/docs/synced-folders/rsync.html):

> The rsync synced folder does a one-time one-way sync from the machine running to the machine being started by Vagrant.

So it is a normal behavior that you're facing: vagrant up syncs one time, and then you have to use `vagrant rsync-auto` to watch for files changes at your host level.


Thank you for taking time for providing informations. i'm closing this issue, feel free to reopen if I did not understand well :)
