### ISSUE TITLE
User/group with NFS

### ISSUE THREAD

**Issue by Freyskeyd** [dduportal/boot2docker-vagrant-box#7]
Hey,

We can mount a NFS synced_folder now.

But permissions are corrupt. With NFS we can't get a proper way to set permissions between docker container and host.

All files created in docker container are `root:staff` instead of `You:staff`.

If anyone have an idea to fix it.

I've tried some tricks:
```
chmod
umask
add user to groups
add group
```

**Comment by dduportal** [comment]
Ok, another issue around that : https://github.com/dduportal/boot2docker-vagrant-box/issues/10. There is solution to use at Vagrantfile level for now.

I'll close that issue to avoid redundancy.

Thanks for the infos !
